version: '3.3'
services:
  adameds-farmasi:
    image: adameds/faramsi-service:dev
    container_name: adameds-farmasi
    ports:
      - 8086:8086
    restart: always
    networks:
        - farmasi-network
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_POOL=${DB_POOL}
networks:
  farmasi-network:
    driver: bridge