services:
  adameds-farmasi:
    image: adameds/faramsi-service:dev
    container_name: adameds-farmasi
    ports:
      - 8086:8086
    restart: always
    networks:
        - farmasi-network
    environment:
      # db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      # redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DATABASE}

    volumes:
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-farmasi/private.key
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-farmasi/public.key
networks:
    farmasi-network:
        driver: bridge