services:
  adameds-farmasi:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/faramsi-service:dev
    container_name: adameds-farmasi
    ports:
      - 8086:8086
    restart: always
    networks:
      - farmasi-network
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      API_BASE: ${API_BASE}
      API_VERSION: ${API_VERSION}
      BASE_URL: ${BASE_URL}
      REKAM_MEDIS_URL: ${REKAM_MEDIS_URL}
      INVENTORY_URL: ${INVENTORY_URL}
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-farmasi/.env.vault
networks:
  farmasi-network:
    driver: bridge
